set(LOCALPINYIN_VERSION_MAJOR 0)
set(LOCALPINYIN_VERSION_MINOR 3)
set(LOCALPINYIN_VERSION_PATCH 7)
set(LOCALPINYIN_VERSION_CHANNEL "dev")

set(LOCALPINYIN_VERSION_NUMERIC
    "${LOCALPINYIN_VERSION_MAJOR}.${LOCALPINYIN_VERSION_MINOR}.${LOCALPINYIN_VERSION_PATCH}"
)

if (LOCALPINYIN_VERSION_CHANNEL STREQUAL "")
    set(LOCALPINYIN_VERSION_PACKAGE "${LOCALPINYIN_VERSION_NUMERIC}")
else()
    set(LOCALPINYIN_VERSION_PACKAGE "${LOCALPINYIN_VERSION_NUMERIC}-${LOCALPINYIN_VERSION_CHANNEL}")
endif()
